### ISSUE TITLE
Workaround for 3.x users

### ISSUE THREAD

**Issue by spartacus04** [cloudsftp/reSnap#12]
I have a remarkable 3.4 and I need to absolutely take screenshots from it.

Since this project looks kinda dead because it's not receiving updates anymore and to work it requires
`lz4` installed on the remarkable (which requires Toltec -> requires a remarkable <= v2.15.1.1189), I just made a PR to reStream that doesn't need `lz4` installed on the remarkable that allows users to screenshot the device.

You can find the PR [here](https://github.com/rien/reStream/pull/94), it's not merged yet (probably because reStream is kinda dead too) but it allows 3.x users to take screenshots and record their screen without installing toltec

**Comment by cloudsftp** [comment]
Thanks for pointing that out.

I allowed users to use this script without `lz4` on the tablet.
Can you point me to a resource, where the requirements for `toltec` are listed?
I couldn't find it myself and `toltec` works fine for me.
But I also had installed previous to the update.

**Comment by spartacus04** [comment]
Hi, you can find the requirements for Toltec [here](https://toltec-dev.org/#install-toltec), it doesn't support 3.x yet because of ddvk-hacks not supporting such versions

**Comment by cloudsftp** [comment]
Damn I missed that warning when I reinstalled `toltec` this morning.
Luckily it didn't brick my device.

Could you kindly confirm that my changes work for your device?
Then I will close this issue.

**Comment by spartacus04** [comment]
Yea sure, i'll try them right now

**Comment by spartacus04** [comment]
Yes, it works however there's a problem where the output image is really dark,

in reStream [#92](https://github.com/rien/reStream/pull/92) someone fixed this by applying the `curves=all='0/0 0.07/1 1/1'` filter to ffmpeg, but applying it to the reSnap script isn't really working in this case. Unfortunately I can't help you with that since I don't really know how to use ffmpeg that well.

**Comment by cloudsftp** [comment]
Thank you.

When I apply the filter, the image is too bright for me.
You can put the string into the `filters` variable in line 16. Like this:

```
filters="curves=all='0/0 0.07/1 1/1'"
```

**Comment by spartacus04** [comment]
If this can help this is the output with a sample file before and after applying the filer. I assume that it lightens up the image too much so it needs to be tuned down a little.
![before](https://github.com/cloudsftp/reSnap/assets/52862005/c4f6eec2-8fe4-44c6-9dcb-53e02a6ea8e8)
![after](https://github.com/cloudsftp/reSnap/assets/52862005/446e52a0-be2b-416f-a6fe-c6497576b5b2)

**Comment by spartacus04** [comment]
Ah ok, thanks for the help

**Comment by cloudsftp** [comment]
Playing with the parameter `x` changes the brightness.
Higher is brighter.

```
filters="curves=all='0/0 x/1 1/1'"
```

Without the filter its perfect for me.
Interesting that it is different for other people.

**Comment by cloudsftp** [comment]
Ok now, it's too dark for me too.
Working on a fix.

**Comment by cloudsftp** [comment]
@spartacus04 could you test the filters in the linked issue?
