### ISSUE TITLE
reMarkable Ferrari not supported

### ISSUE THREAD

**Issue by lisah2u** [cloudsftp/reSnap#22]
When I use the command ./reSnap.sh I get the message that reMarkable Ferrari is not supported.

**Comment by cloudsftp** [comment]
Wich reMarkable do you have?
Is it the new paper pro?

The script expects the remarkable version to either be "reMarkable 1.0" or "reMarkable 2.0"
Your tablet seems to be the version "reMarkable Ferrari", which is bizarre ^^

-------- Original Message --------

**Comment by lisah2u** [comment]
Yes, it is the paper pro.

**Comment by cloudsftp** [comment]
I see.

It's not yet supported. And I don't have access to the hardware, so I won't implement support anytime soon.

You could try to get it running with the same settings as for the reMarkable 2 by editing the script. But I doubt that it will work.

If it works tho, could you please open a PR?

**Comment by lisah2u** [comment]
Doesn't work. Though posting the response here. Thanks, anyway!

fmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with Apple clang version 16.0.0 (clang-1600.0.26.3)
  configuration: --prefix=/opt/homebrew/Cellar/ffmpeg/7.1 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags='-Wl,-ld_classic' --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libaribb24 --enable-libbluray --enable-libdav1d --enable-libharfbuzz --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librist --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox --enable-audiotoolbox --enable-neon
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
Input #0, rawvideo, from 'fd:':
  Duration: N/A, bitrate: 1051315 kb/s
  Stream #0:0: Video: rawvideo (Y1[0][16] / 0x10003159), gray16le, 1872x1404, 1051315 kb/s, 25 tbr, 25 tbn
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> png (native))
[vf#0:0 @ 0x133906060] No filtered frames for output stream, trying to initialize anyway.
Output #0, image2, to '/tmp/reSnap/snapshot_2024-10-14_07-50-30.png':
  Metadata:
    encoder         : Lavf61.7.100
  Stream #0:0: Video: png, rgb24(progressive), 1404x1872, q=2-31, 200 kb/s, 25 fps, 25 tbn
      Metadata:
        encoder         : Lavc61.19.100 png
[out#0/image2 @ 0x60000124c000] video:0KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
[out#0/image2 @ 0x60000124c000] Output file is empty, nothing was encoded(check -ss / -t / -frames parameters if used)
frame=    0 fps=0.0 q=0.0 Lsize=N/A time=N/A bitrate=N/A speed=N/A
feh WARNING: /tmp/reSnap/snapshot_2024-10-14_07-50-30.png does not exist - skipping
feh: No loadable images specified.
See 'man feh' for detailed usage information
