### ISSUE TITLE
sh: line 2: /home/root/head: No such file or directory

### ISSUE THREAD

**Issue by oren** [cloudsftp/reSnap#4]
I am on ubuntu. i scp the head and lz4 to /home/root of my device and i have lz4, ffmpeg, and feh installed on my laptop.

```
~/p/reSnap ./reSnap.sh

ffmpeg version 4.3.1-4ubuntu1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10 (Ubuntu 10.2.0-9ubuntu2)
  configuration: --prefix=/usr --extra-version=4ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
sh: line 2: /home/root/head: No such file or directory
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, bitrate: 525657 kb/s
    Stream #0:0: Video: rawvideo (Y800 / 0x30303859), gray, 1872x1404, 525657 kb/s, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> png (native))
Output #0, image2, to '/tmp/reSnap/snapshot_2021-06-30_20-11-42.png':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: png, gray, 1404x1872, q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc
    Metadata:
      encoder         : Lavc58.91.100 png
frame=    0 fps=0.0 q=0.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
feh WARNING: /tmp/reSnap/snapshot_2021-06-30_20-11-42.png does not exist - skipping
feh: No loadable images specified.
See 'man feh' for detailed usage information
```

**Comment by cloudsftp** [comment]
Can you please tell me, what shell you are using and what OS you are on?
Are you logged in as root?

My suspicion is that in line 122, the `$HOME` maybe got expanded and therefore it is the wrong path.
On the reMarkable there is only `/root` and not `/home/root`.
You could try replacing `\$HOME/` by `/root/` in lines 110 and 139.

**Comment by oren** [comment]
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy
```

---

```
$ uname -a
Linux oren 5.8.0-53-generic #60-Ubuntu SMP Thu May 6 07:46:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
---

```
echo $HOME
=>
/home/oren

echo $head_fb0
=>
dd if=/proc/231/mem bs=4096 skip=474078 count=642 2>/dev/null | tail -c+8 | $HOME/head -c 2628288
```

---
cat ~/.ssh/config
```
Host rm
    HostName 10.0.0.196
    User root

Host rm-usb
    HostName 10.11.99.1
    User root
```

On my laptop I login as oren, on the rm I ssh/login as root

**Comment by cloudsftp** [comment]
Ok I see, the error message says `/home/root` even if there is no such directory, I just reproduced this behavior by removing the executable permission on `head`.
However I can not reproduce your issue.

I read [online](https://unix.stackexchange.com/questions/18061/why-does-sh-say-not-found-when-its-definitely-there) that such a behavior `sh: ...: no such file or directory` could be caused by missing dependencies.
I probably have those dependencies because I installed `head` originally using [entware](https://github.com/Evidlo/remarkable_entware).

You might want to try installing it via `entware` too.

**Comment by oren** [comment]
```
opkg install head
Unknown package 'head'.
Collected errors:
 * opkg_install_cmd: Cannot install package head.
```

**Comment by cloudsftp** [comment]
Sorry, I forgot to mention, the packages name is `coreutils-head`.

Also please remove `~/head` after install so the script uses the version installed via `opkg`.

**Comment by oren** [comment]
```
opkg install coreutils-head
Installing coreutils-head (8.32-6) to root...
Downloading https://bin.entware.net/armv7sf-k3.2/coreutils-head_8.32-6_armv7-3.2.ipk
wget: note: TLS certificate validation not implemented
Collected errors:
 * opkg_install_pkg: Checksum or size mismatch for package coreutils-head. Either the opkg or the package index are corrupt. Try 'opkg update'.
 * opkg_install_cmd: Cannot install package coreutils-head.
 ```

**Comment by cloudsftp** [comment]
Just try running `opkg update` and maybe `opkg upgrade` to update the package list and the programs.

**Comment by oren** [comment]
works! where does it saves my image if i don't specific `-o`?

**Comment by cloudsftp** [comment]
That's great! Thank you for pointing this bug out, I will update the installation instructions now.

If you not specify `-o` it will save the image in `/tmp/reSnap` as `snapshot_*.png`.
If you are on version `2.0` it will stay there. But if you are on `develop` or update to a future release, these files will be deleted automatically.

**Comment by oren** [comment]
i don't see anything on my laptop's /tmp/reSnap

BTW, The first thing i did is commented the last line since i don't want to open feh.

How do i hide all the text I see in STDOUT (unless there is an error, i don't want text)?

**Comment by cloudsftp** [comment]
Hm that's weird maybe there is a problem with `ffmpeg`.

Currently there is no way to hide the STDOUT output.
I tried `./reSnap.sh > /dev/null` but `ffmpeg` writes either to `err` or `warning`.

**Comment by oren** [comment]
got it. it will be nice to have a script that doesn't send anything to
SDTOUT so it will be easier to integrate it with other tools.

**Comment by oren** [comment]
I wonder if it's possible to generate images of the entire notebook or
generate pdf from the entire notebook (with the highlighter as yellow or
any other color).

**Comment by cloudsftp** [comment]
I guess it might be possible but goes way beyond the scope of this project.
The script just grabs the current content of the screenbuffer on the reMarkable.
You might be interested in [this](https://github.com/jmptable/rm-dl-annotated) project.
